site_name: Shutdown.Tools
site_url: https://shutdown.tools
nav:
  - Home: index.md
theme:
  name: material
  features:
    - toc.integrate   # put TOC inside the left sidebar
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: deep orange
      accent: lime
extra_css:
  - assets/stylesheets/custom.css
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
